# Generated by Django 5.2.17 on 2026-09-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('answer', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'query logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=64, unique=True)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reorder_threshold', models.PositiveIntegerField(default=10, help_text='When quantity falls to or below this, the item is flagged.')),
                ('reorder_quantity', models.PositiveIntegerField(default=0, help_text='How much to order when restocking. 0 = auto-suggest.')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='inventory_i_categor_bf879d_idx'), models.Index(fields=['is_active'], name='inventory_i_is_acti_fd4174_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_sku', models.CharField(max_length=64)),
                ('quantity_at_alert', models.PositiveIntegerField()),
                ('threshold_at_alert', models.PositiveIntegerField()),
                ('severity', models.CharField(choices=[('LOW', 'Low stock'), ('OUT', 'Out of stock')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='inventory.item')),
            ],
            options={
                'verbose_name_plural': 'stock alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = stock in, negative = out.')),
                ('reason', models.CharField(choices=[('INITIAL', 'Initial stock'), ('PURCHASE', 'Purchase received'), ('SALE', 'Sale / issued out'), ('ADJUSTMENT', 'Manual adjustment'), ('RETURN', 'Customer return'), ('DAMAGE', 'Damage / loss')], default='ADJUSTMENT', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
